stages:
  - test
  - deploy
  - deploy-start

cache:
  paths:
    - _build/
    - deps/
    - apps/frontend/node_modules
    - rel/

mix:test:
  stage: test
  tags:
    - docker
  image: nikolauska/phoenix:latest
  services:
    - postgres:9.5
  variables:
    POSTGRES_DB: kuikka_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    KUIKKADB_URL: "postgres://postgres:postgres@postgres/kuikka_test"
    MIX_ENV: test
  script:
    - mix setup.min
    - mix db.setup
    - mix test --cover

mix:lint:
  stage: test
  tags:
    - docker
  image: nikolauska/phoenix:latest
  variables:
    MIX_ENV: test
  script:
    - mix setup.min
    - mix lint

mix:release:
  stage: test
  tags:
    - docker
  image: nikolauska/phoenix:latest
  variables:
    MIX_ENV: prod
    NODE_ENV: prod
  script:
    - mix setup.min
    - mix release --warnings-as-errors

coverage:
  stage: deploy
  tags:
    - docker
  image: nikolauska/phoenix:latest
  services:
    - postgres:9.5
  variables:
    POSTGRES_DB: kuikka_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    KUIKKADB_URL: "postgres://postgres:postgres@postgres/kuikka_test"
    MIX_ENV: test
  only:
    - master@osasto-kuikka/kuikka-website
  variables:
    MIX_ENV: test
  script:
    - mix setup.min
    - mix coveralls

deploy:restart:
  stage: deploy
  tags:
    - osastokuikka
    - shell
  only:
    - master@osasto-kuikka/kuikka-website
  variables:
    MIX_ENV: prod
    NODE_ENV: prod
    HOST: "osastokuikka.com"
    PORT: "4000"
  script:
    - mix setup.min
    - mix npm.install
    - mix release
    - rel/kuikka_website/bin/kuikka_website stop
    - rel/kuikka_website/bin/kuikka_website start

deploy:start:
  stage: deploy-start
  tags:
    - osastokuikka
    - shell
  only:
    - master@osasto-kuikka/kuikka-website
  when: manual
  variables:
    MIX_ENV: prod
    NODE_ENV: prod
    HOST: "osastokuikka.com"
    PORT: "4000"
  script:
    - mix setup
    - mix release
    - rel/kuikka_website/bin/kuikka_website start
