language: elixir
elixir: 1.4.4
otp_release: 19.3
addons:
  postgresql: 9.5
script:
  - mix deps.get
  - mix compile
  - mix test
  - mix dialyzer
  - mix credo
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - _build
    - deps
